### ISSUE TITLE
Tokenization of html UTF-8 chars 

### ISSUE THREAD

**Issue by cakelly** [emorynlp/nlp4j-tokenization#9]
I am working on a comparison of tokenizers for microblog texts, and am finding issues with nlpj 1.1.3 (from http://nlp.mathcs.emory.edu/nlp4j/nlp4j-appassembler-1.1.3.tgz). 

This issue involves html-encoded characters such as &amp; and &lt; which are split into separate characters.  This is not a problem with other tokenizers.  E.g. the following text

> I'd like this &amp; that &lt; the other

is parsed as 

```
4   this    this    DT  _   3   dobj    _   O
5   &   &   CC  _   4   cc  _   O
6   amp amp NN  _   4   conj    _   O
7   ;   ;   ,   pos2=:  3   punct   _   O
8   that    that    DT  pos2=WDT    3   dep _   O
9   &   &   CC  pos2=NFP    8   cc  _   O
10  lt  lt  JJ  pos2=NN 8   conj    _   O
11  ;   ;   :   pos2=,  13  punct   _   O
```

**Comment by jdchoi77** [comment]
Thanks for pointing this out; do you mind creating this issue with our merged project:

https://github.com/emorynlp/nlp4j

I'll try to handle these cases for the following version which I'm hoping to release soon.  Thanks.

**Comment by cakelly** [comment]
Will do. There are 4 issues, and now I see theyre not where you want, but I'm moving them.
